"""initial schema

Revision ID: 31fc080423a5
Revises: 
Create Date: 2026-06-28 12:53:38.751479
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import app.models.types  # tipos de columna que cifran PII (Deterministic/Encrypted)


revision: str = '31fc080423a5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('actor_ip', sa.String(length=64), nullable=True),
    sa.Column('actor_key_fp', sa.String(length=16), nullable=True),
    sa.Column('business_id', sa.String(length=36), nullable=True),
    sa.Column('ts', sa.String(length=32), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seq')
    )
    op.create_index('ix_audit_action_created', 'audit_log', ['action', 'created_at'], unique=False)
    op.create_table('businesses',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('business_type', sa.String(length=60), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_phone_number_id', sa.String(length=40), nullable=True),
    sa.Column('notify_phone', sa.String(length=32), nullable=True),
    sa.Column('system_context', sa.Text(), nullable=True),
    sa.Column('assistant_name', sa.String(length=40), nullable=True),
    sa.Column('agent_tone', sa.String(length=16), nullable=False),
    sa.Column('use_emojis', sa.Boolean(), nullable=False),
    sa.Column('agent_language', sa.String(length=8), nullable=False),
    sa.Column('brand_color', sa.String(length=7), nullable=True),
    sa.Column('logo_url', sa.String(length=300), nullable=True),
    sa.Column('opening_hours', sa.JSON(), nullable=False),
    sa.Column('slot_granularity_min', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_closures',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('custom_hours', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=160), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'date', name='uq_closure_business_date')
    )
    op.create_table('conversations',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('customer_phone', app.models.types.DeterministicString(length=255), nullable=False),
    sa.Column('state', sa.Enum('IDLE', 'COLLECTING_SERVICE', 'COLLECTING_PROFESSIONAL', 'COLLECTING_DATETIME', 'COLLECTING_CONTACT', 'CONFIRMING', 'WAITLIST_OFFER', 'MANAGE_BOOKING', 'HUMAN_HANDOFF', name='conversationstate', native_enum=False, length=30), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'customer_phone', name='uq_conversation_business_phone')
    )
    op.create_table('customers',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('phone', app.models.types.DeterministicString(length=255), nullable=False),
    sa.Column('name', app.models.types.EncryptedString(), nullable=True),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'phone', name='uq_customer_business_phone')
    )
    op.create_table('events_log',
    sa.Column('business_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_business_type', 'events_log', ['business_id', 'type'], unique=False)
    op.create_index('ix_events_notified', 'events_log', ['type', 'notified_at'], unique=False)
    op.create_table('inbound_messages',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=128), nullable=False),
    sa.Column('from_phone', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'message_id', name='uq_inbound_business_message')
    )
    op.create_table('resources',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('working_hours', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resources_business', 'resources', ['business_id'], unique=False)
    op.create_table('services',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('buffer_before_min', sa.Integer(), nullable=False),
    sa.Column('buffer_after_min', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_services_business', 'services', ['business_id'], unique=False)
    op.create_table('appointments',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('block_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('block_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'NO_SHOW', name='appointmentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('service_name', sa.String(length=160), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('notes', app.models.types.EncryptedString(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'idempotency_key', name='uq_business_idempotency'),
    sa.UniqueConstraint('resource_id', 'start_at', name='uq_resource_slot')
    )
    op.create_index('ix_appointments_business_start', 'appointments', ['business_id', 'start_at'], unique=False)
    op.create_index('ix_appointments_customer', 'appointments', ['customer_id'], unique=False)
    op.create_index('ix_appointments_reminder', 'appointments', ['reminder_sent_at', 'start_at'], unique=False)
    op.create_table('service_resource',
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id', 'resource_id')
    )
    op.create_table('time_off',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=160), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timeoff_resource_range', 'time_off', ['resource_id', 'start_at', 'end_at'], unique=False)
    op.create_table('waitlist',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('customer_phone', app.models.types.DeterministicString(length=255), nullable=False),
    sa.Column('customer_name', app.models.types.EncryptedString(), nullable=True),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('desired_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('WAITING', 'NOTIFIED', 'FULFILLED', name='waitliststatus', native_enum=False, length=16), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_waitlist_business_status', 'waitlist', ['business_id', 'status'], unique=False)
    op.create_index('ix_waitlist_match', 'waitlist', ['business_id', 'service_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_waitlist_match', table_name='waitlist')
    op.drop_index('ix_waitlist_business_status', table_name='waitlist')
    op.drop_table('waitlist')
    op.drop_index('ix_timeoff_resource_range', table_name='time_off')
    op.drop_table('time_off')
    op.drop_table('service_resource')
    op.drop_index('ix_appointments_reminder', table_name='appointments')
    op.drop_index('ix_appointments_customer', table_name='appointments')
    op.drop_index('ix_appointments_business_start', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index('ix_services_business', table_name='services')
    op.drop_table('services')
    op.drop_index('ix_resources_business', table_name='resources')
    op.drop_table('resources')
    op.drop_table('inbound_messages')
    op.drop_index('ix_events_notified', table_name='events_log')
    op.drop_index('ix_events_business_type', table_name='events_log')
    op.drop_table('events_log')
    op.drop_table('customers')
    op.drop_table('conversations')
    op.drop_table('business_closures')
    op.drop_table('businesses')
    op.drop_index('ix_audit_action_created', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
